### PR TITLE
Improved and updated the French language

### PR DESCRIPTION
**Pull request by azalty**
- Improved some existing translations
- Fixed some node names
- Added missing nodes

It should now be a lot better.
Might not be perfect, but we're closer than ever!

### CODE REVIEW

**Review by maxijabase — DISMISSED** [review]
* don't modify node names
* keep up with the latest pushed changes

**Comment by maxijabase** [comment]
Hello man thank you a lot for your help translation SPCode to the French language.
I've seen you've modified some node names, which is something that the guidelines say you must not do, since the source code calls translations with those names. [Check the guidelines here](https://github.com/SPCodeOrg/spcode-translations#translation-tips-and-guidelines).

Even though the nodes may have funky namings, that's how the phrase is requested in the source code. If the node name gets modified, that phrase stops getting translated.

I was about to push some changes to the default file but I forgot. I basically removed all Java installation related phrases, which means you can replicate that in the French file, and well, other fixes and additions too that you can find in the latest ``default.xml`` file.

**Comment by azalty** [comment]
I modified the node names to match with the ones in the "default" language file. Not sure what you're talking about.

**Comment by maxijabase** [comment]
ohhhhhhhhhhhhhh would you look at that, you're absolutely right, that's fantastic, GREAT
sorry, my bad

whenever you manage to add the latest additions of default.xml this will be merged

**Comment by azalty** [comment]
Should be good now :)

Edit: woops wait a bit

**Comment by azalty** [comment]
Should be good (truly)

**Pull request merged**
